version: 2.1
orbs:
  nais: navikt/nais-deployment@1.5.0
  slack: circleci/slack@3.3.0
  env: christeredvartsen/persist-env@0.0.4
  
executors :
   go:
    docker:
      - image: navikt/deployment-cli:v0.2.0
jobs:
    build:
        working_directory: ~/foreldrepengeplanlegger
        docker:
            - image: circleci/node:latest
        environment:
          MAJOR_VERSION: 2  
        steps:
            - checkout
            
            - env/set-env-var:
                 var-name: RELEASE_VERSION
                 var-value: $MAJOR_VERSION-$CIRCLE_BUILD_NUM-$(git rev-parse --short HEAD)
                 
            - env/set-env-var:
                 var-name: REPO
                 var-value: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME

            - env/set-env-var:
                 var-name: IMAGE
                 var-value: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_PROJECT_REPONAME   
            - run:
                 name: Run npm install
                 command: npm install

            - run:
                 name: Build
                 command: npm run build
          
            - nais/docker-deploy:
                 registry: docker.pkg.github.com
                 image: $IMAGE
                 tag: $RELEASE_VERSION

            - env/persist-env

    dev-deploy:
      executor: go
      steps:
        - nais-deploy:
            template-vars: dev.json
            environment: dev-sbs 
    dev-gcp-deploy:
      executor: go
      steps:
        - nais-deploy:
            template-vars: dev-gcp.json
            environment: dev-gcp   
    prod-gcp-deploy:
      executor: go
      steps:
        - nais-deploy:
            template-vars: prod-gcp.json
            environment: prod-gcp            
    prod-deploy:
       executor: go
       steps:
          - nais-deploy:
             template-vars: prod.json
             environment: prod-sbs

commands:
  nais-deploy:
    parameters:
      template-vars:
        type: string
      environment:
        type: string
    steps:
      - env/attach-env
      - checkout
      - nais/generate-nais-deployment:
          repo: $REPO
          nais-template: naiserator.yaml
          team: teamforeldrepenger
          github-app-id: 20250
          image: docker.pkg.github.com/$IMAGE
          tag: $RELEASE_VERSION
          environment: << parameters.environment >>
          enable-vars: true
          template-vars: << parameters.template-vars >>


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          context: familie-ci 
      - dev-deploy:
          context: NAIS deployment
          filters:
            branches:
              only: master
          requires:
            - build
      - dev-gcp-deploy:
          context: NAIS deployment
          filters:
            branches:
              only: master
          requires:
            - build       
      - hold:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - dev-deploy
     - hold-gcp:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - gcp-deploy        

      - slack/approval-notification:
          webhook: $SLACK
          message: "Godkjenn deploy til prod av $CIRCLE_PROJECT_REPONAME"
          url: https://circleci.com/workflow-run/$CIRCLE_WORKFLOW_WORKSPACE_ID
          requires:
            - dev-deploy

      - prod-deploy:
          context: NAIS deployment
          filters:
            branches:
              only: master
          requires:
            - hold
      - prod-gcp-deploy:
          context: NAIS deployment
          filters:
            branches:
              only: master
          requires:
            - hold-gcp      
