apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: foreldrepengeplanlegger
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
  image: {{image}}
  port: 8080
  replicas:
      min: 2
      max: 2
      disableAutoScaling: true
  liveness:
      path: /health/isAlive
      initialDelay: 60
  readiness:
      path: /health/isReady
      initialDelay: 60
  prometheus:
      enabled: false
      path: /internal/actuator/prometheus
  ingresses:
{{#each ingresses as |url|}}
    - {{url}}
{{/each}}
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  env:
  {{#each env}}
   - name: {{@key}}
     value: "{{this}}"
  {{/each}}
  webproxy: true
