name: Manuell deploy (kun for redirect conf)

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NAMESPACE: teamforeldrepenger
  CLUSTER: dev-gcp

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut repo
        uses: actions/checkout@v2
      - name: Deploy til dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          PRINT_PAYLOAD: true
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ env.CLUSTER }}
          RESOURCE: .deploy/naiserator.yaml
          VAR: url=https://foreldrepengeplanlegger.dev.nav.no
